if (!self.define) {
    let s, e = {};
    const l = (l, i) => (l = new URL(l + ".js", i).href, e[l] || new Promise((e => {
        if ("document" in self) {
            const s = document.createElement("script");
            s.src = l, s.onload = e, document.head.appendChild(s)
        } else s = l, importScripts(l), e()
    })).then((() => {
        let s = e[l];
        if (!s) throw new Error(`Module ${l} didn’t register its module`);
        return s
    })));
    self.define = (i, n) => {
        const r = s || ("document" in self ? document.currentScript.src : "") || location.href;
        if (e[r]) return;
        let u = {};
        const a = s => l(s, r),
            o = {
                module: {
                    uri: r
                },
                exports: u,
                require: a
            };
        e[r] = Promise.all(i.map((s => o[s] || a(s)))).then((s => (n(...s), u)))
    }
}
define(["./workbox-7369c0e1"], (function(s) {
    "use strict";
    self.addEventListener("message", (s => {
        s.data && "SKIP_WAITING" === s.data.type && self.skipWaiting()
    })), s.precacheAndRoute([{
        url: "assets/_arrayPush.949d1e07.js",
        revision: null
    }, {
        url: "assets/_baseClone.1ae22030.js",
        revision: null
    }, {
        url: "assets/_baseFlatten.1b8a9a9c.js",
        revision: null
    }, {
        url: "assets/_baseFor.671df8ff.js",
        revision: null
    }, {
        url: "assets/_baseIsEqual.cca7ad74.js",
        revision: null
    }, {
        url: "assets/_baseOrderBy.365c2f0e.js",
        revision: null
    }, {
        url: "assets/_baseRest.0a5801c8.js",
        revision: null
    }, {
        url: "assets/_commonjs-dynamic-modules.30ae7933.js",
        revision: null
    }, {
        url: "assets/_initCloneObject.91168f35.js",
        revision: null
    }, {
        url: "assets/_isIterateeCall.7435a88e.js",
        revision: null
    }, {
        url: "assets/_overRest.86a13aad.js",
        revision: null
    }, {
        url: "assets/_Uint8Array.82d4fc05.js",
        revision: null
    }, {
        url: "assets/about.52459531.css",
        revision: null
    }, {
        url: "assets/about.f90a7223.js",
        revision: null
    }, {
        url: "assets/AccessTimeRound.fa407395.js",
        revision: null
    }, {
        url: "assets/account.fe4a9b89.js",
        revision: null
    }, {
        url: "assets/addToDesk.49d98345.js",
        revision: null
    }, {
        url: "assets/aes.8e299e6d.js",
        revision: null
    }, {
        url: "assets/animate.5fcc932e.css",
        revision: null
    }, {
        url: "assets/aria.66f3f71c.js",
        revision: null
    }, {
        url: "assets/async-init.4827bb1e.js",
        revision: null
    }, {
        url: "assets/axios.91e25212.js",
        revision: null
    }, {
        url: "assets/backup.01bcfb62.js",
        revision: null
    }, {
        url: "assets/backup.b4f31fe6.css",
        revision: null
    }, {
        url: "assets/baseApi.fc01bad0.js",
        revision: null
    }, {
        url: "assets/baseRequest.b881af11.js",
        revision: null
    }, {
        url: "assets/bg-select.66f63f9d.js",
        revision: null
    }, {
        url: "assets/bg-select.8849a7e6.css",
        revision: null
    }, {
        url: "assets/BrowserGuide.5c928bcd.js",
        revision: null
    }, {
        url: "assets/BrowserGuide.a93ab9b6.css",
        revision: null
    }, {
        url: "assets/CaretBottom.eb9794aa.js",
        revision: null
    }, {
        url: "assets/cloneDeep.3cbd3f2d.js",
        revision: null
    }, {
        url: "assets/Close.c9346f3b.js",
        revision: null
    }, {
        url: "assets/CloseBold.35e7dcc2.js",
        revision: null
    }, {
        url: "assets/common.44d12874.css",
        revision: null
    }, {
        url: "assets/config-provider.35572354.js",
        revision: null
    }, {
        url: "assets/create_login.656547e7.css",
        revision: null
    }, {
        url: "assets/create_login.994910cf.js",
        revision: null
    }, {
        url: "assets/css-vars.b790953f.css",
        revision: null
    }, {
        url: "assets/css.35989968.js",
        revision: null
    }, {
        url: "assets/css.64f23996.js",
        revision: null
    }, {
        url: "assets/css.9423aff0.js",
        revision: null
    }, {
        url: "assets/css.9d4644ca.js",
        revision: null
    }, {
        url: "assets/css.9e9722ea.js",
        revision: null
    }, {
        url: "assets/CustomAdd.1c9e31be.css",
        revision: null
    }, {
        url: "assets/CustomAdd.68b36f25.js",
        revision: null
    }, {
        url: "assets/d-button.33d6ccf9.css",
        revision: null
    }, {
        url: "assets/d-button.975b01f4.js",
        revision: null
    }, {
        url: "assets/d-color.0db1603d.js",
        revision: null
    }, {
        url: "assets/d-color.4e426ccc.css",
        revision: null
    }, {
        url: "assets/d-contextmenu.576ba68d.js",
        revision: null
    }, {
        url: "assets/d-contextmenu.fd6e1540.css",
        revision: null
    }, {
        url: "assets/d-dialog.840c6cfa.js",
        revision: null
    }, {
        url: "assets/d-dialog.d74e6560.css",
        revision: null
    }, {
        url: "assets/d-font-family.127a8e53.js",
        revision: null
    }, {
        url: "assets/d-icon.0893d740.css",
        revision: null
    }, {
        url: "assets/d-icon.af5cac18.js",
        revision: null
    }, {
        url: "assets/d-infinite-scroll.69c647fa.js",
        revision: null
    }, {
        url: "assets/d-infinite-scroll.e7d0aa22.css",
        revision: null
    }, {
        url: "assets/d-radio.c91f2f8c.js",
        revision: null
    }, {
        url: "assets/d-radio.fbed35df.css",
        revision: null
    }, {
        url: "assets/d-scroll-x.7030039a.js",
        revision: null
    }, {
        url: "assets/d-slider.3662bca0.js",
        revision: null
    }, {
        url: "assets/d-slider.37e47760.css",
        revision: null
    }, {
        url: "assets/d-switch.8a9ea11a.css",
        revision: null
    }, {
        url: "assets/d-switch.9f1bb591.js",
        revision: null
    }, {
        url: "assets/d-tabs-x.34b56210.js",
        revision: null
    }, {
        url: "assets/d-tabs-x.39ed9562.css",
        revision: null
    }, {
        url: "assets/d-tabs.9116c806.css",
        revision: null
    }, {
        url: "assets/d-tabs.dd73b910.js",
        revision: null
    }, {
        url: "assets/dayOfYear.81fd7fcd.js",
        revision: null
    }, {
        url: "assets/de.ec7ad64c.js",
        revision: null
    }, {
        url: "assets/debounce.abbfdaeb.js",
        revision: null
    }, {
        url: "assets/defaultNavConfig.7b81c7b6.js",
        revision: null
    }, {
        url: "assets/defaultNavConfig.90e05c16.js",
        revision: null
    }, {
        url: "assets/Drawer.c2e2fd1d.js",
        revision: null
    }, {
        url: "assets/dujitang.2d5d6b5f.js",
        revision: null
    }, {
        url: "assets/el-button.2cb60ae5.css",
        revision: null
    }, {
        url: "assets/el-card.208b2445.css",
        revision: null
    }, {
        url: "assets/el-checkbox-group.987ef89c.css",
        revision: null
    }, {
        url: "assets/el-checkbox.7cab41d0.js",
        revision: null
    }, {
        url: "assets/el-checkbox.aec27a4a.css",
        revision: null
    }, {
        url: "assets/el-col.6b49831e.css",
        revision: null
    }, {
        url: "assets/el-col.bf48eb7b.js",
        revision: null
    }, {
        url: "assets/el-date-picker.8ccf5c29.js",
        revision: null
    }, {
        url: "assets/el-date-picker.d0c7d83a.css",
        revision: null
    }, {
        url: "assets/el-dialog.c73078d2.js",
        revision: null
    }, {
        url: "assets/el-dialog.f4eb42cc.css",
        revision: null
    }, {
        url: "assets/el-drawer.85167f95.js",
        revision: null
    }, {
        url: "assets/el-drawer.f97e7830.css",
        revision: null
    }, {
        url: "assets/el-form-item.912e2c38.js",
        revision: null
    }, {
        url: "assets/el-form-item.d10bb01f.css",
        revision: null
    }, {
        url: "assets/el-icon.b1770749.css",
        revision: null
    }, {
        url: "assets/el-image-viewer.f74efbeb.css",
        revision: null
    }, {
        url: "assets/el-input-number.643e34ac.css",
        revision: null
    }, {
        url: "assets/el-input-number.b7d676fb.js",
        revision: null
    }, {
        url: "assets/el-loading.7c3a3a4a.css",
        revision: null
    }, {
        url: "assets/el-main.0eaee62a.js",
        revision: null
    }, {
        url: "assets/el-main.f5c6a819.css",
        revision: null
    }, {
        url: "assets/el-message-box.d5ceed26.css",
        revision: null
    }, {
        url: "assets/el-message.a1d9903a.css",
        revision: null
    }, {
        url: "assets/el-notification.cf8e1b84.css",
        revision: null
    }, {
        url: "assets/el-overlay.f6b2674f.css",
        revision: null
    }, {
        url: "assets/el-popover.f80de2ca.css",
        revision: null
    }, {
        url: "assets/el-progress.1f9bfc72.css",
        revision: null
    }, {
        url: "assets/el-progress.3a42d846.js",
        revision: null
    }, {
        url: "assets/el-radio.74b38810.js",
        revision: null
    }, {
        url: "assets/el-radio.94b07b0d.css",
        revision: null
    }, {
        url: "assets/el-select.e009b2dc.css",
        revision: null
    }, {
        url: "assets/el-select.e274bb48.js",
        revision: null
    }, {
        url: "assets/el-skeleton-item.2cbc8fed.css",
        revision: null
    }, {
        url: "assets/el-skeleton-item.3776d71d.js",
        revision: null
    }, {
        url: "assets/el-switch.1d3ca0ca.js",
        revision: null
    }, {
        url: "assets/el-switch.4d96cdcc.css",
        revision: null
    }, {
        url: "assets/el-tabs.5164aac9.css",
        revision: null
    }, {
        url: "assets/el-tooltip.89296c46.js",
        revision: null
    }, {
        url: "assets/el-upload.125a730c.js",
        revision: null
    }, {
        url: "assets/el-upload.ae1d280e.css",
        revision: null
    }, {
        url: "assets/element-plus.3dfc0062.css",
        revision: null
    }, {
        url: "assets/eventBus.68d45896.js",
        revision: null
    }, {
        url: "assets/fingerprint2.472393d4.js",
        revision: null
    }, {
        url: "assets/FitScreenRound.001d7f0f.js",
        revision: null
    }, {
        url: "assets/flatten.65ace828.js",
        revision: null
    }, {
        url: "assets/focus-trap.e600e472.js",
        revision: null
    }, {
        url: "assets/foodMenus.34a925ef.js",
        revision: null
    }, {
        url: "assets/globalSearch.6bc5de8d.js",
        revision: null
    }, {
        url: "assets/gridScrollEvent.b53f47f2.js",
        revision: null
    }, {
        url: "assets/hardware-info.ec50f284.js",
        revision: null
    }, {
        url: "assets/hasIn.0ceeb413.js",
        revision: null
    }, {
        url: "assets/hisBackup.548c12df.css",
        revision: null
    }, {
        url: "assets/hisBackup.6b206e80.js",
        revision: null
    }, {
        url: "assets/HomeContextmenu.6014d2ea.css",
        revision: null
    }, {
        url: "assets/HomeContextmenu.fc234f65.js",
        revision: null
    }, {
        url: "assets/homeIcon.d07425ea.js",
        revision: null
    }, {
        url: "assets/HomeNavGroup.3eb6172f.js",
        revision: null
    }, {
        url: "assets/HomeNavGroup.be9e9d4d.css",
        revision: null
    }, {
        url: "assets/HomeNotesFixed.b5a0901f.css",
        revision: null
    }, {
        url: "assets/HomeNotesFixed.cc4e2728.js",
        revision: null
    }, {
        url: "assets/HomeSearchList.c2da49e9.js",
        revision: null
    }, {
        url: "assets/HomeSearchList.c5356a34.css",
        revision: null
    }, {
        url: "assets/HomeSearchSuggest.5364f78f.css",
        revision: null
    }, {
        url: "assets/HomeSearchSuggest.b1f3e1c5.js",
        revision: null
    }, {
        url: "assets/icon.3ea8d182.js",
        revision: null
    }, {
        url: "assets/icon.77457eb3.css",
        revision: null
    }, {
        url: "assets/icon.8b835c88.js",
        revision: null
    }, {
        url: "assets/IconEdit.5454a2b5.js",
        revision: null
    }, {
        url: "assets/identity.737b3aaf.js",
        revision: null
    }, {
        url: "assets/index.00ad4f9d.css",
        revision: null
    }, {
        url: "assets/index.029a6b4f.js",
        revision: null
    }, {
        url: "assets/index.051c1656.css",
        revision: null
    }, {
        url: "assets/index.07d957b6.js",
        revision: null
    }, {
        url: "assets/index.0ada893d.css",
        revision: null
    }, {
        url: "assets/index.0dab37b3.css",
        revision: null
    }, {
        url: "assets/index.0e1148e8.js",
        revision: null
    }, {
        url: "assets/index.14b43c35.js",
        revision: null
    }, {
        url: "assets/index.16828acb.js",
        revision: null
    }, {
        url: "assets/index.176a125e.js",
        revision: null
    }, {
        url: "assets/index.18dbb15e.js",
        revision: null
    }, {
        url: "assets/index.1aebf6ea.css",
        revision: null
    }, {
        url: "assets/index.1b78c202.js",
        revision: null
    }, {
        url: "assets/index.1d46d4e1.js",
        revision: null
    }, {
        url: "assets/index.1f445754.js",
        revision: null
    }, {
        url: "assets/index.2681f46b.js",
        revision: null
    }, {
        url: "assets/index.2e893c48.js",
        revision: null
    }, {
        url: "assets/index.3379b85c.css",
        revision: null
    }, {
        url: "assets/index.3aa4392a.js",
        revision: null
    }, {
        url: "assets/index.3ad15718.css",
        revision: null
    }, {
        url: "assets/index.3da25773.css",
        revision: null
    }, {
        url: "assets/index.401d2f91.css",
        revision: null
    }, {
        url: "assets/index.45b942c8.js",
        revision: null
    }, {
        url: "assets/index.466a8266.js",
        revision: null
    }, {
        url: "assets/index.47a56f13.js",
        revision: null
    }, {
        url: "assets/index.49c1cafb.css",
        revision: null
    }, {
        url: "assets/index.4e5ff846.js",
        revision: null
    }, {
        url: "assets/index.52524422.js",
        revision: null
    }, {
        url: "assets/index.53013133.css",
        revision: null
    }, {
        url: "assets/index.534437f3.js",
        revision: null
    }, {
        url: "assets/index.54e5ea91.js",
        revision: null
    }, {
        url: "assets/index.5a5a289c.js",
        revision: null
    }, {
        url: "assets/index.5bc72676.js",
        revision: null
    }, {
        url: "assets/index.5ccb56e3.css",
        revision: null
    }, {
        url: "assets/index.5d41bfcf.js",
        revision: null
    }, {
        url: "assets/index.61097b9b.css",
        revision: null
    }, {
        url: "assets/index.6190cf91.css",
        revision: null
    }, {
        url: "assets/index.6727caac.js",
        revision: null
    }, {
        url: "assets/index.678fad5a.css",
        revision: null
    }, {
        url: "assets/index.69cfdc42.css",
        revision: null
    }, {
        url: "assets/index.6a012a65.css",
        revision: null
    }, {
        url: "assets/index.6d6dd2b2.css",
        revision: null
    }, {
        url: "assets/index.6e845614.css",
        revision: null
    }, {
        url: "assets/index.6eaa4e86.js",
        revision: null
    }, {
        url: "assets/index.72bec9e8.js",
        revision: null
    }, {
        url: "assets/index.742e3cb2.js",
        revision: null
    }, {
        url: "assets/index.76df867f.js",
        revision: null
    }, {
        url: "assets/index.77cf9a11.js",
        revision: null
    }, {
        url: "assets/index.7c0d977d.js",
        revision: null
    }, {
        url: "assets/index.7dd10c51.css",
        revision: null
    }, {
        url: "assets/index.7de5cde8.js",
        revision: null
    }, {
        url: "assets/index.7eda866d.js",
        revision: null
    }, {
        url: "assets/index.837ee212.js",
        revision: null
    }, {
        url: "assets/index.84c26abd.css",
        revision: null
    }, {
        url: "assets/index.8720847e.js",
        revision: null
    }, {
        url: "assets/index.87f7d0e4.js",
        revision: null
    }, {
        url: "assets/index.8a15c747.css",
        revision: null
    }, {
        url: "assets/index.8ba13591.js",
        revision: null
    }, {
        url: "assets/index.8cbf67a5.js",
        revision: null
    }, {
        url: "assets/index.8f4298f2.js",
        revision: null
    }, {
        url: "assets/index.8fa282a1.css",
        revision: null
    }, {
        url: "assets/index.a432878a.css",
        revision: null
    }, {
        url: "assets/index.a7298621.js",
        revision: null
    }, {
        url: "assets/index.a7745e2a.js",
        revision: null
    }, {
        url: "assets/index.aacc54d8.js",
        revision: null
    }, {
        url: "assets/index.acf04de2.css",
        revision: null
    }, {
        url: "assets/index.ae6751c2.css",
        revision: null
    }, {
        url: "assets/index.af1ea92d.css",
        revision: null
    }, {
        url: "assets/index.bd01dcfa.js",
        revision: null
    }, {
        url: "assets/index.c15ec867.css",
        revision: null
    }, {
        url: "assets/index.c210f77a.js",
        revision: null
    }, {
        url: "assets/index.c554612f.css",
        revision: null
    }, {
        url: "assets/index.c7370e6c.js",
        revision: null
    }, {
        url: "assets/index.c89b0165.js",
        revision: null
    }, {
        url: "assets/index.c90cc0e4.js",
        revision: null
    }, {
        url: "assets/index.c942a8df.css",
        revision: null
    }, {
        url: "assets/index.ca3d31b2.js",
        revision: null
    }, {
        url: "assets/index.cb15136f.css",
        revision: null
    }, {
        url: "assets/index.cb9f48ad.js",
        revision: null
    }, {
        url: "assets/index.cc4e09e7.js",
        revision: null
    }, {
        url: "assets/index.cdbb23f9.js",
        revision: null
    }, {
        url: "assets/index.d235e992.js",
        revision: null
    }, {
        url: "assets/index.d23a0eff.js",
        revision: null
    }, {
        url: "assets/index.d3d6fdbf.js",
        revision: null
    }, {
        url: "assets/index.d44a5a70.js",
        revision: null
    }, {
        url: "assets/index.d7cc6868.css",
        revision: null
    }, {
        url: "assets/index.df325e17.js",
        revision: null
    }, {
        url: "assets/index.e56fc127.js",
        revision: null
    }, {
        url: "assets/index.e6e26ddb.js",
        revision: null
    }, {
        url: "assets/index.e9a8d9c2.js",
        revision: null
    }, {
        url: "assets/index.eb3fea09.js",
        revision: null
    }, {
        url: "assets/index.ed6e81ca.js",
        revision: null
    }, {
        url: "assets/index.f31b513a.js",
        revision: null
    }, {
        url: "assets/index.f4f7491a.js",
        revision: null
    }, {
        url: "assets/index.f9be212e.js",
        revision: null
    }, {
        url: "assets/index.fc4c0c3e.js",
        revision: null
    }, {
        url: "assets/index.fe139383.css",
        revision: null
    }, {
        url: "assets/indexdb.a2b9d265.js",
        revision: null
    }, {
        url: "assets/init.9b24bee1.js",
        revision: null
    }, {
        url: "assets/install.0e1fb9e6.js",
        revision: null
    }, {
        url: "assets/install.ce0fd30e.js",
        revision: null
    }, {
        url: "assets/isArrayLikeObject.26380556.js",
        revision: null
    }, {
        url: "assets/isEqual.296380c7.js",
        revision: null
    }, {
        url: "assets/isObject.a01dee34.js",
        revision: null
    }, {
        url: "assets/itab.eac3c33d.js",
        revision: null
    }, {
        url: "assets/jikipedia.70ff3e41.js",
        revision: null
    }, {
        url: "assets/jingtuitui.5644e1e0.js",
        revision: null
    }, {
        url: "assets/KLine.56989934.js",
        revision: null
    }, {
        url: "assets/lang.8a31e446.js",
        revision: null
    }, {
        url: "assets/lang.ca5a1720.css",
        revision: null
    }, {
        url: "assets/layout.5848236a.js",
        revision: null
    }, {
        url: "assets/layout.88dae80e.css",
        revision: null
    }, {
        url: "assets/localforage.2a1ae675.js",
        revision: null
    }, {
        url: "assets/main.354a692e.js",
        revision: null
    }, {
        url: "assets/movieCalendar.26003b56.js",
        revision: null
    }, {
        url: "assets/open.670c1833.js",
        revision: null
    }, {
        url: "assets/orderBy.4b744bff.js",
        revision: null
    }, {
        url: "assets/ossClient.3d42266e.js",
        revision: null
    }, {
        url: "assets/panel-time-pick.6d2aa6d4.js",
        revision: null
    }, {
        url: "assets/PictureFilled.875791a4.js",
        revision: null
    }, {
        url: "assets/PinOff16Regular.6c319d64.js",
        revision: null
    }, {
        url: "assets/popup.ee9256a4.js",
        revision: null
    }, {
        url: "assets/popup.f05e876d.css",
        revision: null
    }, {
        url: "assets/position.8ddd1c03.js",
        revision: null
    }, {
        url: "assets/public-api.6a0debad.js",
        revision: null
    }, {
        url: "assets/pwa.f31090eb.js",
        revision: null
    }, {
        url: "assets/Refresh.dd54cee1.js",
        revision: null
    }, {
        url: "assets/RefreshRight.be739b02.js",
        revision: null
    }, {
        url: "assets/reset.c55ed9b6.js",
        revision: null
    }, {
        url: "assets/rgbaster.0a390c88.js",
        revision: null
    }, {
        url: "assets/save_config.cbe33c4d.js",
        revision: null
    }, {
        url: "assets/scroll.4972bdba.js",
        revision: null
    }, {
        url: "assets/search.088318c0.js",
        revision: null
    }, {
        url: "assets/Search.37b8df57.js",
        revision: null
    }, {
        url: "assets/Select.07e4eb6a.js",
        revision: null
    }, {
        url: "assets/sidebar.6ff32bcb.css",
        revision: null
    }, {
        url: "assets/sidebar.ec3fb319.js",
        revision: null
    }, {
        url: "assets/sortable.esm.bf8db74c.js",
        revision: null
    }, {
        url: "assets/sponsor.0b32950e.css",
        revision: null
    }, {
        url: "assets/sponsor.db1f22da.js",
        revision: null
    }, {
        url: "assets/sport.cc5aad2f.js",
        revision: null
    }, {
        url: "assets/statistics.a738debd.js",
        revision: null
    }, {
        url: "assets/stock.bd4b8210.js",
        revision: null
    }, {
        url: "assets/strings.e32d5a08.js",
        revision: null
    }, {
        url: "assets/style.d69d81d7.js",
        revision: null
    }, {
        url: "assets/theme.3b34c946.js",
        revision: null
    }, {
        url: "assets/theme.aa405ed8.css",
        revision: null
    }, {
        url: "assets/throttle.0dfde511.js",
        revision: null
    }, {
        url: "assets/time.22acd78f.css",
        revision: null
    }, {
        url: "assets/time.944a7f30.js",
        revision: null
    }, {
        url: "assets/timeFormat.2ad7f500.js",
        revision: null
    }, {
        url: "assets/timezone.aed506dc.js",
        revision: null
    }, {
        url: "assets/todayEnglish.583b5dd6.js",
        revision: null
    }, {
        url: "assets/todayShici.da9bbb1a.js",
        revision: null
    }, {
        url: "assets/topsearch.7f46afb5.js",
        revision: null
    }, {
        url: "assets/TranslateRound.6288cc78.js",
        revision: null
    }, {
        url: "assets/Trends.1ff44bb2.js",
        revision: null
    }, {
        url: "assets/typescript.72bf8adc.js",
        revision: null
    }, {
        url: "assets/unionConfig.49171fa7.js",
        revision: null
    }, {
        url: "assets/useSta.b98c784e.js",
        revision: null
    }, {
        url: "assets/utc.01108fd0.js",
        revision: null
    }, {
        url: "assets/validator.05a5fb38.js",
        revision: null
    }, {
        url: "assets/version.8d34b113.js",
        revision: null
    }, {
        url: "assets/versionChangelog.0d99a409.js",
        revision: null
    }, {
        url: "assets/versionNotice.ea178545.js",
        revision: null
    }, {
        url: "assets/vuedraggable.umd.514d0ade.js",
        revision: null
    }, {
        url: "assets/wallpaper.3a2b0557.js",
        revision: null
    }, {
        url: "assets/wallpaper.7bf4d1cf.js",
        revision: null
    }, {
        url: "assets/wallpaper.a853638a.css",
        revision: null
    }, {
        url: "assets/wallpaperDb.e3a7e00b.js",
        revision: null
    }, {
        url: "assets/weather.b106cfc7.js",
        revision: null
    }, {
        url: "assets/weatherApi.bab704ad.js",
        revision: null
    }, {
        url: "assets/website.2111b3d7.js",
        revision: null
    }, {
        url: "assets/widget-icon-item.0b19e53c.css",
        revision: null
    }, {
        url: "assets/widget-icon-item.eb544202.js",
        revision: null
    }, {
        url: "assets/workbox-window.prod.es5.d2780aeb.js",
        revision: null
    }, {
        url: "assets/xiayigejiaqi.ad1190e6.js",
        revision: null
    }, {
        url: "assets/xyzrank.6915478a.js",
        revision: null
    }, {
        url: "assets/yiyan.54a1ffc2.js",
        revision: null
    }, {
        url: "assets/zh-cn.140881fa.js",
        revision: null
    }, {
        url: "assets/zh.65b14249.js",
        revision: null
    }, {
        url: "index.html",
        revision: "1524ba6e823186e323c7e5620a29d833"
    }, {
        url: "js/color-thief.js",
        revision: "d7850c6bc5816817b4832122071c0f6e"
    }, {
        url: "js/iconfont.js",
        revision: "aa82227d0727ad7edb266e2f2d056bee"
    }, {
        url: "js/init.js",
        revision: "c0dce9c9714d411aacc403db691625c1"
    }, {
        url: "popup.html",
        revision: "feda81e7abf2ef8b50798a702b033303"
    }, {
        url: "privacy.html",
        revision: "31e756ee677f2bdb4ec57d28c21588d7"
    }, {
        url: "webfont/index.css",
        revision: "51454b068b5357a246b335043bf1af98"
    }, {
        url: "favicon.ico",
        revision: "ab768d1a42b3383239d125e1a554e0fb"
    }, {
        url: "robots.txt",
        revision: "cd9cd94aaa699e0a16e692b6bb16f672"
    }, {
        url: "logo/icon_192.png",
        revision: "e6828113c6e915f20de4ff4a1e35c66b"
    }, {
        url: "logo/icon_512.png",
        revision: "368faf83a68d86c56e800284ebdc74f0"
    }, {
        url: "manifest.webmanifest",
        revision: "bcaff9bee85789cc0674d6bd8e2fe5ef"
    }], {}), s.cleanupOutdatedCaches(), s.registerRoute(new s.NavigationRoute(s.createHandlerBoundToURL("index.html")))
}));